# Generated by Django 3.2.6 on 2021-08-29 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entryDate',
            field=models.DateField(default=datetime.date(2021, 1, 1)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('fan', 'fantastic'), ('gre', 'great'), ('goo', 'good'), ('neu', 'neutral'), ('dow', 'down'), ('ann', 'annoyed'), ('ove', 'overwhelmed')], default='neu', max_length=20),
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
