# Generated by Django 3.2.6 on 2021-08-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210829_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('fantastic', 'Fantastic'), ('great', 'Great'), ('good', 'Good'), ('neutral', 'Neutral'), ('down', 'Down'), ('annoyed', 'Annoyed'), ('overwhelmed', 'Overwhelmed')], default='neutral', max_length=20),
        ),
    ]
